# Generated by Django 3.2.6 on 2023-03-03 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='capsules',
            fields=[
                ('reuse_count', models.IntegerField()),
                ('water_landings', models.IntegerField()),
                ('land_landings', models.IntegerField()),
                ('last_update', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('cid', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='launches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch', models.CharField(max_length=20)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capsule.capsules')),
            ],
        ),
    ]
